name: Create Wiki Pages from Issues

on:
  issues:
    types: [opened, edited]

jobs:
  create-wiki-page:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Git configuration
        run: |
          git config --global user.name 'github-actions[bot]'
          git config --global user.email 'github-actions[bot]@users.noreply.github.com'

      - name: Get issue details
        id: issue_details
        run: |
          echo "TITLE=${{ github.event.issue.title }}" >> $GITHUB_ENV
          echo "BODY=${{ github.event.issue.body }}" >> $GITHUB_ENV
          echo "AUTHOR=${{ github.event.issue.user.login }}" >> $GITHUB_ENV
          echo "DATE=$(date +"%Y-%m-%d")" >> $GITHUB_ENV

      - name: Generate markdown content
        run: |
          SLUG="${{ env.TITLE }}-${{ env.DATE }}"
          PAGE_PATH="pages/$SLUG.md"
          
          echo "# ${{ env.TITLE }}" > $PAGE_PATH
          echo "### Author: ${{ env.AUTHOR }}" >> $PAGE_PATH
          echo "### Date: ${{ env.DATE }}" >> $PAGE_PATH
          echo "## About" >> $PAGE_PATH
          echo "${{ env.BODY }}" >> $PAGE_PATH
          echo "## Examples" >> $PAGE_PATH
          echo "Here are some examples of how to use this page:" >> $PAGE_PATH
          echo "```" >> $PAGE_PATH
          echo "Example 1: ..." >> $PAGE_PATH
          echo "Example 2: ..." >> $PAGE_PATH
          echo "```" >> $PAGE_PATH

      - name: Commit and push changes
        run: |
          git add pages/
          git commit -m "Added page: ${{ env.TITLE }}-${{ env.DATE }} and updated homepage" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git main

      - name: Update homepage with new page link
        run: |
          HOMEPAGE="pages/index.md"
          echo "### New page added: [${{ env.TITLE }}]($SLUG.md)" > $HOMEPAGE
          git add $HOMEPAGE
          git commit -m "Updated homepage with latest page" || echo "No changes to commit"
          git push https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com/${{ github.repository }}.git main
